config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root'static_pages#index'
  resources :business_listings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :user do
    resources :business_listings, only: :index
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
    end
  end
  resources :messages, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_listing.rb
class BusinessListing < ApplicationRecord
	mount_uploader :photo, PhotoUploader
	belongs_to :user
	validates :user_id,
			 	:title,
				:location,
				:revenue,
				:cash_flow,
				:business_description,
				:property_size,
				:years_estd,
				:property_type,
				:business_location,
				:premise_details,
				:competition,
				:expansion_potential,
				:employees,
				:trading_hours,
				:support_training,
				:financing_available,
				:reason_for_selling, presence: true
				
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :business_listings
   mount_uploader :photo, PhotoUploader
   acts_as_messageable
    def mailboxer_email(object)
      email
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :mailbox, :conversation

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name,:middle_name, :last_name, :phone_number,:country_select, :email, :password, :password_confirmation, :name, :photo) }
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name,:middle_name, :last_name, :phone_number,:email, :password, :password_confirmation, :current_password, :name, :photo) }
    end

  private

   def conversation
     @conversation ||= mailbox.conversations.find(params[:id])
   end

     rescue_from ActiveRecord::RecordNotFound do
     flash[:warning] = 'Resource not found.'
     redirect_back_or root_path
   end

  def redirect_back_or(path)
   redirect_to request.referer || path
  end
end

app/controllers/business_listings_controller.rb
class BusinessListingsController < ApplicationController
		before_action :authenticate_user!, only: [:new, :create,:edit]
		def new
			@business_listing = BusinessListing.new
		end

		def create
    	@business_listing = current_user.business_listings.build(business_params)
      @business_listing.save
      if @business_listing.valid?
				flash[:success] = "Your listing has been successfully created and sent to the admin to verify it!!"
        redirect_to root_path
      else
        render :new
      end
		end

		def show
			@business_listings = BusinessListing.find(params[:id])
		end

		def edit
			@business_listings = BusinessListing.find(params[:id])
		end

		private

		def business_params
			params.require(:business_listing).permit(
				:photo,
				:user_id,
				:title,
				:location,
				:revenue,
				:cash_flow,
				:business_description,
				:property_size,
				:years_estd,
				:property_type,
				:business_location,
				:premise_details,
				:competition,
				:expansion_potential,
				:employees,
				:trading_hours,
				:support_training,
				:financing_available,
				:reason_for_selling)
		end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index]
  before_action :get_box, only: [:index]
  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    end

  def show

  end
  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end
  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end
  private
  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  def new

  end

  def create
    recipients = []
    params[:recipients].each do |f|
      if f.split(':').first === 'User'
        recipient = User.find(f.split(':').last)
        recipients << recipient
      elsif f.split(':').first === 'BusinessListing'
        recipient = BusinessListing.find(f.split(':').last)
        recipients << recipient
      end
    end
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
     @business_listing = BusinessListing.all.where(approve: true)
	end
end

app/controllers/user/business_listings_controller.rb
class User::BusinessListingsController < ApplicationController
  def index
    @business_listing = current_user.business_listings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name}</option>"
    end
    s.html_safe
  end
end

app/views/business_listings/index.html.erb
<div class = "row">
	<div class = "col-md-4">
		<h3>Account Details</h3>
		<ul>
			<li><%= link_to 'Edit Account',  edit_user_registration_path %></li>
			<li><%= link_to 'Cancel My Account',cancel_user_registration_path, data: { confirm: "Are you sure?" }, method: :delete %></li>
			<li><%= link_to "My jobs", user_business_listings_path %></li>
		</ul>
	</div>
	<div class = "col-md-8">
		<h3>Account Type: Buyer, Seller</h3>
<div class="panel panel-default">
  <div class="panel-heading">Seller Account</div>
  <div class="panel-body">
  	<%= link_to 'Create Listings',new_business_listing_path %>
  	<%= link_to 'Payment History', root_path %>
  </div>
</div>
<div class = "panel panel-default">
	<div class = "panel-heading">Buyer Account</div>
	<div class = "panel-body">
		<%= link_to 'Messages From Seller', root_path %>
	</div>
</div>
</div>
</div>

app/views/business_listings/new.html.erb
<%= simple_form_for @business_listing do |f| %>
<h3>Create your listings</h3>
<p>Unless stated as required ( * ), all the fields are optional. We understand that anonymity and privacy may sometimes be key considerations when selling a business - therefore business names and location details do not have to be shown.
To achieve the best results please ensure you fill out as much information as possible.
Please note: Do not use ALL CAPITAL LETTERS.</p>
	<div class="row">
	    <div class = "col-md-4">
	    	<%= f.input :photo%>
			<%= f.input :title%>
			<%= f.input :location %>
			<%= f.input :revenue%>
			<%= f.input :cash_flow %>
			<%= f.input :business_description %>
			<%= f.input :property_size %>
			<%= f.input :years_estd %>
		</div>
		<div class = "col-md-4">

			<%= f.input :property_type %>
			<%= f.input :business_location %>
			<%= f.input :premise_details%>
			<%= f.input :competition %>
			<%= f.input :expansion_potential %>
		</div>
		<div class = "col-md-4">

			<%= f.input :employees %>
			<%= f.input :trading_hours %>
			<%= f.input :support_training %>
			<%= f.input :financing_available %>
			<%= f.input :reason_for_selling %>
			<%= f.submit 'Post', class:'btn btn-success', data: { disable_with: "Posting..." } %>
		</div>

	</div>
<% end %>

app/views/business_listings/show.html.erb
<%= image_tag @business_listings.photo, class: "image" %></br>
<%= @business_listings.title %><br>
<%= @business_listings.location %><br>
<%= @business_listings.revenue %><br>
<%= @business_listings.cash_flow %><br>

<h3>Business Description</h3>
<%= @business_listings.business_description %><br>


<h3>Property Details</h3>
<%= @business_listings.property_size %><br>
<%= @business_listings.years_estd %><br>
<%= @business_listings.property_type%><br>

<h3>Other Details</h3>
<%= @business_listings.business_location%><br>
<%= @business_listings.premise_details%><br>
<%= @business_listings.competition%><br>
<%= @business_listings.expansion_potential%><br>
<%= @business_listings.employees%><br>

<h3>Operation Details</h3>
<%= @business_listings.trading_hours%><br>
<%= @business_listings.support_training%><br>
<%= @business_listings.financing_available%><br>

<h3>Miscellaneous</h3>
<%= @business_listings.reason_for_selling%><br />
<br />


<% if user_signed_in? %>
<p>Want to buy business? send message to the seller<p>
  <%= link_to'Send Message', conversations_path %>
<% else %>
        <%= form_for(:user, :url => session_path(:user)) do |f| %>
        <div class = "field">
        <%= f.text_field :first_name, autofocus: true, class: 'input-form',placeholder: 'First Name' %>
        </div>
        <div class = "field">
          <%= f.text_field :middle_name, autofocus: true, class: 'input-form',placeholder: 'Middle Name' %>
        </div>
        <br />
        <div class = "field">
          <%= f.text_field :last_name, autofocus: true, class: 'input-form',placeholder: 'Last Name' %>
        </div>
        <br />
        <div class = "field">
          <%= f.text_field :phone_number, autofocus: true,class: 'input-form', placeholder: 'Phone Number' %>
        </div>
        <br />
        <div class="field">
          <%= f.email_field :email, autofocus: true, class: 'input-form', placeholder: 'Email' %>
        </div>
        <br />
        <div class="field">
          <%= f.password_field :password, autocomplete: "off", class: 'input-form',placeholder: 'Password' %>
        </div>
        <br />
        <div class="field">
          <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Password Again'%>
        </div>
        <div class = "field">
            <%= f.label :Select_your_country %><br>
             <%= f.country_select :country_select, as: :country_select, required: true %>
        </div>
        <br />
        <div class="actions">
          <%= f.submit "Sign up" %>
        </div>
        <% end %>


        <% end %>

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
      <% end %>

  </div>

  <p><%= render 'conversations/participants', conversation: conversation ,:formats => :html%></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= participant.first_name %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<% page_header "Your Conversations" %>
  <div class="row">
      <div class="col-sm-3">
        <ul class="nav nav-pills nav-stacked">
          <%= mailbox_section 'inbox', @box %>
          <%= mailbox_section 'sent', @box %>
          <%= mailbox_section 'trash', @box %>
        </ul>
      </div>
      <div class="col-sm-9">
        <% if @box == 'trash' %>
          <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
        data: {confirm: 'Are you sure?'} %></p>
        <% end %>
        <ul class="list-group">
          <%= render partial: 'conversations/conversation', collection: @conversations %>
        </ul>
        <p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>
      </ul>
    </div>
  </div>

app/views/conversations/show.html.erb
<% page_header "Conversation" %>

<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.first_name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Businessforsale</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
<div class = "container-fluid">
    <div class = "row">
      <div class = "col-xs-8"></div>
          <div class = "nav_wrapper">
            <div class = "col-xs-4">
              <% if user_signed_in? %>
              <%= current_user.email %>
              <%= link_to 'My Account |',business_listings_path %>
              <%= link_to 'Log Out',destroy_user_session_path, method: :delete %>
              <% else %>
              <%= link_to 'Sign Up |', new_user_registration_path %>
              <%= link_to 'Log In', new_user_session_path %>
              <% end %>
            </div>
          </div>
      </div>
    </div>
      <div class = "jumbotron">
        <h3>Buying and Selling</h3>
        <p>Register to create your business</p>
      </div>

    <div id = "warp">
      <nav class= "navbar navbar-default">
       <div class = "container-fluid">
         <div class = "navbar-header">
            <button type = "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target = "#bs-example-navbar-collapse-1" aria-expanded= "false">
              <span class = "sr-only">Toggle navigation</span>
              <span class = "icon-bar"></span>
              <span class = "icon-bar"></span>
              <span class = "icon-bar"></span>
            </button>
            <div class = "collapse navbar-collapse text-center" id = "bs-example-navbar-collapse-1">
              <ul class = "nav navbar-nav navbar-right">
                <li><%= link_to 'Business For Sale', root_path %></li>
                <li><%= link_to 'Franchise Opportunity', root_path%></li>
                <li><%= link_to 'Business Broker', root_path%></li>
              </ul>
            </div>
        </div>
      </div>
    </nav>
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <br>
      <div id = "footer">
        <footer class= "footer text-center">
     <div class="container">
    <div class = "row">
      <div class = "col-xs-12 col-md-3">
        <h4>Contact</h4>
        <%= link_to 'businessforsale.com','/' %>
      </div>
      <div class = "col-xs-12 col-md-3">
        <h4>Services</h4>
        <ul>
          <li>Buy a business</li>
          <li>Buy a franchise</li>
          <li>Sell a Business</li>
        </ul>

      </div>
      <div class = "col-xs-12 col-md-3">
        <h4>© Business For Sale</h4>
        <p>All Rights Reserved</p>
      </div>
      <div class = "col-xs-12 col-md-3">
        <h4>Member of </h4>
        <p>International Franchise Association</p>

      </div>
    </div>
  </div>
</footer>


 </div>
  </body>
</html>

app/views/messages/new.html.erb
<% page_header "Start Conversation" %>

<%= form_tag messages_path, method: :post do %>
  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject' %>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'recipients', 'Choose recipients' %>
    <%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control chosen-it' %>
  </div>

  <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>

app/views/static_pages/index.html.erb
<h3>Business</h3>
  <div class="row">
  <% @business_listing.each do |item| %>
  <div class = "post-box">
    <div class = "col-md-4">
    <div class = "post-heading">
      <h5>Title</h5>
        <%= item.title %>
    </div>
    <div class = "post-body">
      <%= image_tag item.photo, class: "image" %>
      <h5>Location</h5>
      <%= item.location %><br>
    </div>
    <div class = "post-footer">
      <%= link_to 'Read More', business_listing_path(item) %>
    </div>
</div>
</div>
  <% end %>

</div>

app/views/user/business_listings/index.html.erb
<% @business_listing.each do |business_listing| %>
<%= image_tag business_listing.photo, class: "image" %>
  <%= business_listing.title %>
  <%= business_listing.location %>
    <%= link_to 'Read More', business_listing_path(business_listing) %>
<% end %>